version: "3.3"
services:
    backend:
        image: fastapi_test
        build:
            context: ./
        ports:
            - "8888:8888"
        command: uvicorn main:app --reaload --host 0.0.0.0 --port 80